### ISSUE TITLE
[1.3.6] Could not find a template file for BodyComponent

### ISSUE THREAD

**Issue by afuno** [github/actionview-component#83] opened 2019-10-21 21:42 UTC
For version 1.3.5 everything is fine. The problem appeared in version 1.3.6. Rails 6.0.0.

---

I have a simple component. Only `content` is transferred to it. After upgrading to version 1.3.6, I started getting the following error:

> NotImplementedError - Could not find a template file for BodyComponent.

**Comment by joelhawksley** [comment] 2019-10-21 21:48
Uh oh! Can you provide a failing test?

**Comment by afuno** [comment] 2019-10-21 21:53
@joelhawksley I can show you the code of my component:

```ruby
class BodyComponent < ActionView::Component::Base
  validates :content, presence: true

  def initialize(*); end
end
```

```slim
= content_tag :body, class: 'best classes'
  = content
```

```slim
= render(BodyComponent)
```

**Comment by joelhawksley** [comment] 2019-10-21 22:09
@afuno might you be able to open a PR with a failing test? Your code looks fine to me.

**Comment by bdtomlin** [comment] 2019-10-24 16:38
I have had the same issue with v 1.3.5 and v 1.3.6, but only in a staging environment (basically production settings). I have not been able to duplicate it in development, but downgrading to 1.3.4 resolves it.

**Comment by joelhawksley** [comment] 2019-11-04 20:39
@afuno might you be able to test this against `master`? I'm curious to know where we stand on this problem.

**Comment by afuno** [comment] 2019-11-06 20:07
@joelhawksley The error based on the code from the master branch is still present.

I do not understand what could be the problem. I use your library in several applications. And only one application has this problem. All applications are similar in structure.

See, I cut the code to a minimum:

```slim
/ app/views/layouts/cinema/main.html.slim
doctype html
html
  head
  = render(BodyComponent)
    | 123
```

And there is a problem. If I comment out the line with render, then everything will be fine. I do not understand how this is possible.

And this problem is really absent in version 1.3.5.

**Comment by joelhawksley** [comment] 2019-11-06 20:21
@afuno I've tried to reproduce this and still can't seem to. Are you seeing the error in local development?

This is the branch I'm working on, for what it's worth: https://github.com/github/actionview-component/tree/83-missing-template

**Comment by afuno** [comment] 2019-11-06 20:22
@joelhawksley Yes, the problem is with local development.

**Comment by afuno** [comment] 2019-11-06 20:24
@joelhawksley After version 1.3.5, something was done, which causes this error.

**Comment by afuno** [comment] 2019-11-06 20:31
Changed the component code:

```ruby
class BodyComponent < ActionView::Component::Base
  def initialize(*); end
end
```

The template is completely empty. That is, the component doesn't accept anything, doesn't wrap anything, and returns nothing.

And the error is still present...

**Comment by afuno** [comment] 2019-11-06 20:36
@joelhawksley https://github.com/github/actionview-component/compare/v1.3.5...v1.3.6

A search of the modified files yielded the following:

https://github.com/github/actionview-component/compare/v1.3.5...v1.3.6#diff-4ea3d395eff742fa0d8952d23a16d377L123-L138

**Comment by joelhawksley** [comment] 2019-11-06 20:42
@afuno might you be able to reproduce this on https://github.com/joelhawksley/actionview-component-demo?

**Comment by afuno** [comment] 2019-11-06 21:00
@joelhawksley I could not reproduce. Too many things. I sent you an invite to the application. 

Update gem version in gemfile. Run through:

```
foreman start -f Procfile.dev
```

**Comment by joelhawksley** [comment] 2019-11-06 22:46
❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ 

HUGE thanks to @afuno here! We were able to figure out the source of this bug: file paths with other periods in them _besides_ the suffix of the component file.

I'll have a fix for this shortly.

**Comment by joelhawksley** [comment] 2019-11-06 23:13
@afuno the fix is in `master`. Can you make sure it works for you?

I'll try to get a release out tomorrow.

**Closed** 2019-11-06 23:13 UTC
Labels: help wanted

**Comment by afuno** [comment] 2019-11-06 23:18
@joelhawksley I checked - everything is fine. Thank you.

**Comment by topherfangio** [comment] 2019-11-07 03:25
@joelhawksley Just hit this error myself and can totally wait for a new version tomorrow; just curious, it seems that there are a bunch of other changes between 1.3.6 and now. Will this be a 1.3.7 release, or more like a 1.4 release?

**Comment by joelhawksley** [comment] 2019-11-07 03:49
@topherfangio I don't hold especially strong opinions about SemVer. What would you suggest?

**Comment by topherfangio** [comment] 2019-11-07 03:58
@joelhawksley I like SemVer 😄 

Specifically, we're building a larger project based off of AV:C and I'm a bit afraid to try out master at the moment because there's so many changes, and...at the moment, we're overriding a bunch of code to get it to work, so I'm kinda **assuming** that master will break things.

Whereas I would assume a 1.3.6 to 1.3.7 bump would really just be bug fixes like this one here. And most of the time, our `Gemfile`s are set to something like `~> 1.3` so that they get all 1.3.x upgrades "automatically".

But, I also realize that you're pretty early in the project and a lot is changing. Honestly, I start most projects at 0.1.0 or something and build up from there so that people don't mistake it for being "stable".

That said, you've already started the versioning, so jumping backward would be really silly, so I'd say keep going.

But if you could ensure that point releases are *mostly* bug fixes, that would be awesome 😄

**Comment by joelhawksley** [comment] 2019-11-07 15:58
@topherfangio that's helpful context! 

You're right that we're in an early place and that things are changing a lot. It's been hard for us to know what will be a breaking change and what won't be due to our still evolving set of test cases! I do think that in this case we've made enough changes to warrant going to `1.4.0`.

On another note, would you be able to share what overrides you've made and why? If you'd rather share them privately, my email is joelhawksley@github.com ❤️

**Comment by topherfangio** [comment] 2019-11-07 16:10
@joelhawksley Sure thing! I actually shared this a while back. It's changed a bit since then, but the basic concept (and the overrides) are the same: 

https://gist.github.com/topherfangio/76615f32f7ebb25e3caa03741cb13a59

**Comment by topherfangio** [comment] 2019-11-07 16:25
@joelhawksley To expand upon that slightly, if we could fix this line to add `self` to the `view_context.capture` call and then add a `after_validate` hook, I wouldn't need to override anything (except the `content` method to make it public for sub-components).

https://gist.github.com/topherfangio/76615f32f7ebb25e3caa03741cb13a59#file-better_component-rb-L17

**Comment by joelhawksley** [comment] 2019-11-07 23:40
@topherfangio thanks for sharing that! (again)

I'd be open to a PR that adds `self` to `view_context.capture`, as well as one that adds hooks. 

I'm also not against making `content` protected, if not public.

Feel free to file issues for any of these ❤️
